Add postgres and create user table
Project-Siew-dai/sd-api pull request #3
Opened 2021-09-08 14:52 UTC by ShenyiCui

Created user database "siewdai"
Created user table

To Create Database:
`npm run db:create`

To migrate user model from JS to Postgres:
`npm run db:migrate`

resolve #1 
resolve #2

2021-09-08 16:00 UTC, oliviajohansen requested changes
Change to Typescript

2021-09-11 05:23 UTC, MarcusTXK commented
> Change to Typescript

Thanks for the feedback, Shenyi and I have update the files to typescript as well as update the file structures.

2021-09-11 05:30 UTC, MarcusTXK commented on config/config.js
> +require('dotenv').config();
We had to disable `@typescript-eslint/no-var-requires` as we could not use import syntax in js file. Is this way of accessing the env variables acceptable?

2021-09-11 18:38 UTC, oliviajohansen reviewed
Some comments.

2021-09-11 18:38 UTC, oliviajohansen commented on src/server.ts
> +  db.authenticate().then(() => console.log('Database Successfully Connected'));
there is an error`SequelizeConnectionError: Connection terminated unexpectedly` when i run `npm run dev`. This is possibly because this line has to be awaited. So create a dbUtils file to export an async fn:
export async function authenticate() {
   await db.authenticate...
}
and call authenticate() in this file.

Also when you passed the sequelize instance from db/index.ts to the model when you created it, the model handles connections to the database so there is no need to explicitly authenticate/connect to db in server.ts. But for now we will still call authenticate() to test that there are no errors when connecting to the db.

2021-09-12 05:29 UTC, MarcusTXK commented on src/server.ts
> +  db.authenticate().then(() => console.log('Database Successfully Connected'));
Okay got it, thanks for the feedback, we have implemented the changes as requested.

2021-09-12 06:33 UTC, oliviajohansen approved these changes
Minor changes but lgtm

2021-09-12 06:33 UTC, oliviajohansen commented on src/db/index.ts
> +  dialect: 'postgres',
host: DB_HOST ref https://sequelize.org/master/manual/getting-started.html or any reason it was intentionally omitted?

2021-09-12 06:33 UTC, oliviajohansen commented on src/server.ts
>  const port = 3000;
remove this and use the port in env file

2021-09-12 07:52 UTC, daongochieu2810 commented on package.json
> +    "dotenv": "^10.0.0",
I think its better if we use exact version i.e "dotenv": "10.0.0" to keep all dependencies ver consistent
Also please add an .nvmrc file to keep npm version consistent

2021-09-12 07:52 UTC, daongochieu2810 commented on README.md
> +5. Run `npm run db:migrate` to migrate models.
Once u add .nvmrc, can add an instruction to run `nvm use` here

2021-09-12 07:52 UTC, daongochieu2810 commented on src/models/User.ts
> +    tableName: 'users',
tablename seems to be inconsistent here and in the migration file. I think u dont need this magic string, just put a static method `getTableName` in this class, or any other way as long as there is only 1 source of truth for this tablename

2021-09-12 07:52 UTC, daongochieu2810 commented on src/models/index.ts
> +fs.readdirSync(__dirname)
Im not sure why we need file operations here? If you want to export all model data/metadata through this entry point, we can just use import/export syntax right?

2021-09-12 08:05 UTC, oliviajohansen commented on src/models/index.ts
> +fs.readdirSync(__dirname)
Yes possible but it will be very tedious when we start to add associations between models Eg `Event.hasMany(User, { foreignKey: 'eventId' })` . With this file we have access to all models at once. See https://stackoverflow.com/questions/32592189/code-explanation-fs-from-sequelize-express-example

2021-09-12 08:27 UTC, MarcusTXK commented on src/db/index.ts
> +  dialect: 'postgres',
Apologies for that, it wasn't ommitted intentionally, we will add it in.

2021-09-12 08:34 UTC, daongochieu2810 commented on src/models/index.ts
> +fs.readdirSync(__dirname)
Then we would need to use string key to access the model i.e models['User']. I think this works but this file still `export { default as User } from './User';`

2021-09-12 08:44 UTC, oliviajohansen commented on src/models/index.ts
> +fs.readdirSync(__dirname)
> Then we would need to use string key to access the model i.e models['User']
I think model.default.name is already a string

> but this file still `export { default as User } from './User';`
Ya isnt it so that we export all model data through this entry point?

2021-09-12 09:16 UTC, daongochieu2810 commented on src/models/index.ts
> +fs.readdirSync(__dirname)
If the purpose of this is to prevent manually putting import/export statements in this entry point, then yes I agree we should have this. But I'm still seeing User model being exported manually, even with `models` holding `User` being exported after that. And `model.default.name` is not what we want, we want the literal key string 'User' to access the User model

2021-09-12 09:35 UTC, oliviajohansen commented on src/models/index.ts
> +fs.readdirSync(__dirname)
> purpose of this is to prevent manually putting import/export statements

Purpose is to prevent manually putting import statements only

> `model.default.name` is not what we want, we want the literal key string 'User' 

How do you know `model.default.name` is not the model name 'User'?

2021-09-12 10:13 UTC, daongochieu2810 commented on src/models/index.ts
> +fs.readdirSync(__dirname)
Why dont we also do for exports then?

2021-09-12 10:14 UTC, daongochieu2810 commented on src/models/index.ts
> +fs.readdirSync(__dirname)
Actually I think it will be super useful if we have IOC here, which will do smth like this, but let leave it to another PR. We can move this dicussion to that PR

2021-09-12 10:24 UTC, oliviajohansen commented on src/models/index.ts
> +fs.readdirSync(__dirname)
yes we should

2021-09-12 10:32 UTC, oliviajohansen commented on src/models/index.ts
> +fs.readdirSync(__dirname)
ok nice you create the issue

2021-09-12 13:37 UTC, daongochieu2810 approved these changes
lgtm

2021-09-13 02:43 UTC, oliviajohansen commented on README.md
> +6. Install nvm on your machine
We should run nvm use before using npm to get the correct version of npm to install dependencies. Steps 6-8 should be before step 1

2021-09-15 08:12 UTC, merged